### PR TITLE
adding a launch file for position controllers

### PR DESCRIPTION
**Pull request by nlyubova**
let's add this launch file for position controllers, since asked by partners

Now, *renamed !

### CODE REVIEW

**Comment by jokla** [comment]
Thanks!

**Comment by mikaelarguedas** [comment]
Thanks!
Feel free to merge it whenever you want

**Comment by nlyubova** [comment]
I'll do the same for Nao if you do not mind (by the way, it is tested for Nao but not yet for Romeo)

**Comment by nlyubova** [comment]
https://github.com/ros-aldebaran/nao_dcm_robot/pull/11

**Pull request merged**
