### PR TITLE
Updating the latest URDF for Romeo

### PR DESCRIPTION
**Pull request by nlyubova**
based on the one generated from Naoqi thanks to Sebastien

### CODE REVIEW

**Comment by nlyubova** [comment]
do not merge it for now

**Comment by jokla** [comment]
Hi Natalia!

Do you know what is actually changing with respect to the last URDF? 
Is it valid for Romeo in Rennes too? ( the legs are the old ones).
Taking a quick look at it,  it seems that all the frame orientations are changed?  But it is not just that, some values are different.

Thanks!!

**Comment by nlyubova** [comment]
it is re-generated from the last Naoqi, so it's related to changes in Naoqi. At least the version of Boost has changed, so some values should be more accurate, but I cannot give more details

Right that there are few changes in orientations,  Do not merge it for now, we'll check them first

**Comment by jokla** [comment]
Ok thanks for the answer. For now I will keep the old URDF then.

**Pull request closed without merging**
