### PR TITLE
updating URDF for eyes including inertia matrices and orientation

### PR DESCRIPTION
**Pull request by nlyubova**
with this commit, Romeo will not explode in Gazebo ! :)

### CODE REVIEW

**Comment by nlyubova** [comment]
@mikaelarguedas do you agree to merge it?

**Comment by mikaelarguedas** [comment]
This PR is just to add dummy inertia for gazebo purposes, these values are arbitrary and don't have any physical meaning is that right ?
The only problem I see is that these values will be overwritten next time we generate the xacro/URDF files.
Would you mind adding these to the generation script instead of the generated files ?
I created a function which does exactly that in https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/generate_urdf.py#L209.
So adding a `add_dummy_inertia` call in [this if](https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/generate_urdf.py#L119) should do the trick.

Thanks!

**Comment by nlyubova** [comment]
Theses values are from JuanJo (and Gazebo works for him ): after asking him why Romeo does explode in Gazebo he has shared his updated URDF with me :) 

By the way, I've found out that all inertia matrices and some masses are slightly different :) How can we update them here ? how to re-generate your values?

**Comment by mikaelarguedas** [comment]
Yes 1e-9 is the default value people put to basically say "no inertia" (gazebo uses 10 significant digits). You should have strictly the same behaviour in gazebo by using the values added by `add_dummy_inertia`.
To regenerate the URDFs you should have an export_urdf function in alrobotmodel. (I don't have access to naoqi libs so I don't have the exact function call).
You can then run `rosrun naoqi_tools generate_urdf.py -x xacro -i <PATH_OF_THE_URDF_FROM_ALROBOTMODEL>`
For more details you can refer to [the README](https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/scripts/README_generate_urdf.py.rst)

**Comment by nlyubova** [comment]
cool, then how can we update ALROBOTMODEL ? :)) since many values are not correct, even mass

**Comment by mikaelarguedas** [comment]
I think we should first make sure that alrobotmodel is not up to date (maybe the library has been updated but the URDFs not generated in a while). BTW I think the export_urdf executable will be in almodelutils and not alrobotmodel as I said earlier.

Can you verify that alrobotmodel is outdated ? if it is, we should ask motion if they can update it with the newest values because this impacts much more than URDFs (Choregraphe etc).

**Comment by mikaelarguedas** [comment]
I think we can merge it as is for now and update the export tools once it has been updated upstream in Aldeb libs.

+1

**Pull request closed without merging**
